version: '3'

rpc:
    listen: 'tcp://127.0.0.1:6001'

http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        debug: true
        supervisor:
            max_worker_memory: 100

server:
    command: 'php app.php'
    relay: pipes

centrifuge:
  proxy_address: tcp://127.0.0.1:10001
  grpc_api_address: tcp://127.0.0.1:10000
  pool:
    num_workers: 3

service:
  centrifugo:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 1
    command: "./centrifugo --config=centrifugo.json"
